-- sound / text
-- xerestrasza
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666000','Help! I am trapped within this tree! I require aid!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17490','1','0','0','SAY_XERESTRASZA_YELL_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666001','Thank you! I could have not held out for much longer. A terrible thing has happened here.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17491','1','0','0','SAY_XERESTRASZA_YELL_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666002','We believed that the Sanctum was well fortified, but we were not prepareted for the nature of this assault.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17492','0','0','0','SAY_XERESTRASZA_SAY_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666003','The Black Dragonkin materialized from thin air, and set upon us before we could react.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17493','0','0','0','SAY_XERESTRASZA_SAY_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666004','We did not stand a chance. As my brethren perished around me, I managed to retreat hear and bar the entrance.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17494','0','0','0','SAY_XERESTRASZA_SAY_3');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666005','They slaughtered us with cold efficiency, but the true focus of their interest seemed to be the eggs kept here in the sanctum.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17495','0','0','0','SAY_XERESTRASZA_SAY_4');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666006','The commander of the forces on the ground here is a cruel brute named Zarithrian. But I fear there are greater powers at work.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17496','0','0','0','SAY_XERESTRASZA_SAY_5');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666007','In their initial assault I caught a glimpse of their true leader, a fearsome full-grown Twilight Dragon.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17497','0','0','0','SAY_XERESTRASZA_SAY_6');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666008','I know not the extent of their plans heroes, but I know this: they cannot be allowed to succeed!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17498','0','0','0','SAY_XERESTRASZA_SAY_7');
 
-- Halion
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666100','Meddlesome insects, you\'re too late! The Ruby Sanctum is lost.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17499','1','0','0','SAY_HALION_SPAWN');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666101','Your world teeters on the brink of annihilation. You will all bear witness to the coming of a new age of destruction!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17500','1','0','0','SAY_HALION_AGGRO');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666102','Another hero falls.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17501','1','0','0','SAY_HALION_SLAY_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666103','Ha Ha Ha!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17502','1','0','0','SAY_HALION_SLAY_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666104','Relish this victory mortals, for it will be your last. This world will burn with the Master\'s return!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17503','1','0','0','SAY_HALION_DEATH');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666105','Not good enough!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17504','1','0','0','SAY_HALION_BERSERK');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666106','The heavens burn!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17505','1','0','0','SAY_HALION_SPECIAL_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666107','Beware the shadow!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17506','1','0','0','SAY_HALION_SPECIAL_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666108','You will find only suffering within the realm of Twilight. Enter if you dare.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17507','1','0','0','SAY_HALION_PHASE_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666109','I am the light AND the darkness! Cower mortals before the Herald of Deathwing!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17508','1','0','0','SAY_HALION_PHASE_3');
 
-- Zarthrian
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666200','Alexstrasza has chosen capable allies. A pity that I must end you!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17512','1','0','0','SAY_ZARITHRIAN_AGGRO');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666201','You thought you stood a chance?',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17513','1','0','0','SAY_ZARITHRIAN_SLAY_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666202','It\'s for the best.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17514','1','0','0','SAY_ZARITHRIAN_SLAY_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666203','Halion! I\'m...aah!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17515','1','0','0','SAY_ZARITHRIAN_DEATH');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666204','Turn them to ash, minions!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17516','1','0','0','SAY_ZARITHRIAN_SPECIAL_1');
 
-- baltharus
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666300','Ah, the entertainment has arrived...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17520','1','0','0','SAY_BALTHARUS_AGGRO');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666301','Baltharus leaves no survivors!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17521','1','0','0','SAY_BALTHARUS_SLAY_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666302','This world has enough heroes!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17522','1','0','0','SAY_BALTHARUS_SLAY_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666303','I...didn\'t see that coming...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17523','1','0','0','SAY_BALTHARUS_DEATH');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666304','Twice the pain and half the fun!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17524','1','0','0','SAY_BALTHARUS_SPECIAL_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666305','Your power wanes, ancient one! Soon, you will join your friends!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17525','1','0','0','SAY_BALTHARUS_YELL');
 
-- saviana
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666400','You will suffer for this intrusion...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17528','1','0','0','SAY_SAVIANA_AGGRO');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666401','As it should be!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17529','1','0','0','SAY_SAVIANA_SLAY_1');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666402','Halion will be pleased...',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17530','1','0','0','SAY_SAVIANA_SLAY_2');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666403','<screaming>',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17531','1','0','0','SAY_SAVIANA_DEATH');
replace into `script_texts` (`entry`, `content_default`, `content_loc1`, `content_loc2`, `content_loc3`, `content_loc4`, `content_loc5`, `content_loc6`, `content_loc7`, `content_loc8`, `sound`, `type`, `language`, `emote`, `comment`) VALUES('-1666404','Burn in the master\'s flame!',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,'17532','1','0','0','SAY_SAVIANA_SPECIAL_1');